theme: minima
title: Larry Coons has a blog 
author: LarryCoons
email: larrycoons@larrycoons.com
description: > # this means to ignore newlines until "baseurl:"
  I have created this as a part of the github tutorial and I hope I can learn some things and bring my
friends along for the ride. We need to learn how to get the word out!

# social links
twitter_username: larryallencoons
github_username:  larrycoons

show_excerpts: true # set to false to remove excerpts on the homepage
